### PR TITLE
README: macOS homebrew

### PR DESCRIPTION
**Pull request by gaoyifan**
https://github.com/Homebrew/homebrew-core/pull/4724

### CODE REVIEW

**Comment by zmwangx** [comment]
Homebrew isn't a service for prebuilt binaries (although we do offer optional prebuilt binaries in certain cases), FYI.

**Comment by gaoyifan** [comment]
maybe we should use homebrew as plan B....

**Comment by zmwangx** [comment]
I'm all for adding Homebrew instructions to README (even a Homebrew badge for people who like that of stuff ), just saying it shouldn't be under the section "prebuilt binaries".

**Comment by xiaq** [comment]
Please move the instruction to the "Building Elvish" section and make it clear that it will build the last release version of elvish (as opposed to HEAD).

**Pull request merged**
