### PR TITLE
fix Elvish Dies with Specific Key Sequence (#391)

### PR DESCRIPTION
**Pull request by HeavyHorst**
this should fix issue #391

### CODE REVIEW

**Comment by xiaq** [comment]
Hi, thanks for uncovering and fixing this!

However, although this patch fixes the crash, it doesn't give a meaningful semantics to forms like `x = y = foo`. There could be two choices:

1. Make this a syntax error.

2. Assign both `x` and `y`.

I think 2. is quite useful, but for the sake of fixing the crash I would happily accept a PR for 1. as well.

**Comment by HeavyHorst** [comment]
Yeah, you're right.
2. should work now.

```
~> a = b = c = d = e = 100
~> echo $a $b $e
100 100 100
```

**Comment by xiaq** [comment]
Hi, that was pretty quick :)

However, this is not a good implementation of 2. Elvish supports assignments of multiple variables, like `a b = lorem ipsum`. To implement 2, it should be extended to support forms like `a b = x y = lorem ipsum`. You are only dealing with `a = b = lorem`, and you also made forms like `a b c = lorem`, which is illegal, legal.

It's fine if 2 is a bit tricky to get right and you only implement 1 for the sake of fixing the crash.

**Comment by HeavyHorst** [comment]
Oh, haven't thought about these edge cases.
I will make it a syntax error for now.

We should perhaps create a new issue to support the other assignment cases.

**Comment by xiaq** [comment]
Hi, I see that you have made this into a syntax error. However, the checking is better done when encountering the `=` instead of within `addLHS`.

**Comment by xiaq** [comment]
Thanks for fixing this. Beware that GitHub does not send me notifications when you modify your PR, you need to add a comment when you have done a requested change.

**Pull request merged**
