### PR TITLE
use has-env to detect E:XDG_DATA_HOME properly

### PR DESCRIPTION
**Pull request by tw4452852**
Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM. See my [comment](https://github.com/elves/elvish/pull/1537#issuecomment-1124505434) on a related pull-request.

**Comment by xiaq** [comment]
The existing code is working as intended; the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) explicitly documents that XDG_DATA_HOME being empty and non-existent are to be treated as the same:

> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

**Comment by krader1961** [comment]
> the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) explicitly documents that XDG_DATA_HOME being empty and non-existent are to be treated as the same

I would argue the spec shouldn't be "protecting" users from doing stupid things like exporting an XDG env var with an empty string as its value. But since the spec dictates that behavior we should, of course, be compliant. However, note that the pending P.R. that fixes the bug where an env var modified using `tmp` is incorrectly reverted to an empty string if the var didn't already exist was the trigger for this P.R. The question is whether we want to

a) require people to write conditions like `if (and (has-env XDG_DATA_HOME) (eq $E: XDG_DATA_HOME ""))`, or

b) continue to expand non-existing env vars to an empty string (something that is a notorious source of bugs)?

**Comment by tw4452852** [comment]
Actually, I am just curious about the scenario in which the user exports `XDG_DATA_HOME` with an empty string...

**Comment by krader1961** [comment]
> Actually, I am just curious about the scenario in which the user exports XDG_DATA_HOME with an empty string

It's something that happens far too often using POSIX compatible shells (e.g., `bash` and `ksh`) due to the many problems with the POSIX shell standard. The POSIX shell standard pretty much guarantees someone will inadvertently export an env var with an empty string as its value. Which is why standards like the XDG spec explicitly state that the empty string should be treated as if the env var didn't exist.

**Comment by tw4452852** [comment]
Make sense, thanks @krader1961 .

**Comment by xiaq** [comment]
See my comment in https://github.com/elves/elvish/pull/1537#issuecomment-1140482929.

**Pull request closed without merging**
