### PR TITLE
Implement str:join

### PR DESCRIPTION
**Pull request by krader1961**
This presumes PR #928 has been merged; thus, only the last commit is relevant.

### CODE REVIEW

**Comment by zzamboni** [comment]
It seems that this should somehow be coalesced with the existing `joins` function, which is implemented here: https://github.com/elves/elvish/blob/master/pkg/eval/builtin_fn_str.go#L286

I'm not sure how I feel about Go library functions that duplicate functionality of existing builtins. Maybe one should just be an alias for the other? @xiaq any thoughts about this?

**Comment by krader1961** [comment]
Note that `joins` is considerably more limited and annoying, IMHO:

```
~/projects/3rd-party/elvish> joins : x (float64 111.222333444555666777888999) y [a '' b] '' c [] d
Exception: want 1 or 2 arguments, got 9
[tty], line 1: joins : x (float64 111.222333444555666777888999) y [a '' b] '' c [] d
~/projects/3rd-party/elvish> put x (float64 111.222333444555666777888999) y [a '' b] '' c [] d | joins :
Exception: join wants string input, got !!float64
~/projects/3rd-party/elvish> e = ?(joins : (float64 2))
~/projects/3rd-party/elvish> joins : [x $e]
Exception: join wants string input, got exception

```

My version handles float64 as well as any other type that implements the elvish `Stringer` interface:

```
~/projects/3rd-party/elvish> str:join : x (float64 111.222333444555666777888999) y [a '' b] '' c [] d
▶ x:111.22233344455567:y:a::b::c:d
~/projects/3rd-party/elvish> e = ?(joins : (float64 2))
~/projects/3rd-party/elvish> str:join : x (float64 111.222333444555666777888999) y [a '' b] '' c [] d $e
▶ 'x:111.22233344455567:y:a::b::c:d:?(fail ''!!float64 cannot be iterated'')'
```

It doesn't, however, read the args from a pipe at the moment --- I'll add that capability:

```
~/projects/3rd-party/elvish> put x y | str:join :
▶ ''
```

**Comment by krader1961** [comment]
I've modified the `str:join` implementation to read from stdin if only a separator string is provided as an argument so you can now do `put a b | str:join :` or `str:join : a b`.

**Comment by krader1961** [comment]
BTW, @xiaq, I recognize that my choice of signature for this function is controversial. I won't be hurt if you argue it should use `type Inputs` and behave like  the `joins` command with regard to how arguments are specified. I actually wrote a version of this function which works that way. Ultimately I think the idiom this establishes is preferable. It can even be applied to `count` in a backward compatible fashion by special casing one argument, if it isn't a list, as a string whose char count should be returned.

**Comment by krader1961** [comment]
@xiaq You should ignore this PR until PR #928 is merged. At which point I'll rebase and open a new PR. I'm going to leave this open for the moment in case anyone wants to comment about the API divergence from established builtins like `joins`.

@zzamboni Note that the `str:` namespace has other functions that mirror existing builtins. For example, `str:has-prefix` mirrors `has-prefix`. Yet they are not explicitly documented as analogs. They are also implemented identically implicitly rather than explicitly. That is, they both directly delegate to the Go `strings.HasPrefix()` function but neither is defined in terms of the other which is a source of potential confusion and bugs.

**Comment by krader1961** [comment]
@zzamboni See also #576 where @xiaq documents the intent to replace builtins such as `joins` with a `str:join`. How best to do so while minimizing transition pain is an open question.

**Comment by zzamboni** [comment]
@krader1961 fair enough - thanks for the pointer! I agree it would be best to have the functions within the corresponding namespace eventually.

**Comment by krader1961** [comment]
A week has gone by and there haven't been any comments. So close this until PR #928 is merged at which time I'll open a new PR.

**Pull request closed without merging**
