### PR TITLE
killDirLeft

### PR DESCRIPTION
**Pull request by aeosynth**

### CODE REVIEW

**Comment by aeosynth** [comment]
fixes #325. probably names are bad. this is my first published go code.

**Comment by xiaq** [comment]
Hi, thank you for the pull request, but I am not going to merge it for the following reasons:

1. This makes the behavior of ^W inconsistent with ^Left and ^Right.

2. This approach is not customizable. What if someone wants ^W to stop at `-` instead of `/`?

A good way to implement this is to let the user specify the set of word separators (currently it is defined by `unicode.IsSpace`). I haven't got around to implementing this though.

As for the naming per se, `kill-path-component-left` is a better name IMO.

**Comment by aeosynth** [comment]
would you want one or many sets of word seperators? eg should it be possible for ^W and ^Left  to behave differently?

**Comment by xiaq** [comment]
I don't like the idea for ^W and ^Left to use different sets of separators. The idea is that they both operate on "words", and they should agree on what a word is. It's easy to explain them to users this way.

This is, however, only about what I would ship in the default setting. On the other hand, I will support customization in the aspect. I opened #333.

**Pull request closed without merging**
