### PR TITLE
Convert to go mod

### PR DESCRIPTION
**Pull request by kenshaw**
Converts dependency management to Go modules, and updates to latest
dependencies.

### CODE REVIEW

**Comment by xiaq** [comment]
Thanks for sending me the PR but unfortunately I am not going to accept it at the moment.

Elvish always supports the last two stable releases of Go. In this case, both 1.11 and 1.12 do have module support but neither have them on by default, requiring the use of the `GO111MODULE` environment variable.

The next stable release of Go, 1.13 will have module support on by default, which means that Elvish will switch to go.mod when Go 1.14 is released.

**Comment by kenshaw** [comment]
Hi @xiaq -- please note that when `go.mod` is in the root of the repository, and `GO111MODULE` is not set (ie, the "default" environment), it defaults to `GO111MODULE=auto`. This causes Go to use `go.mod`.

The following is the output of a simple build of `elvish` demonstrating this behavior:

```sh
ken@ken-desktop:~$ unset GOPATH GOROOT_BOOTSTRAP GO111MODULE
ken@ken-desktop:~$ env |grep '^GO'
ken@ken-desktop:~$ git clone https://github.com/kenshaw/elvish.git
Cloning into 'elvish'...
remote: Enumerating objects: 24142, done.
remote: Total 24142 (delta 0), reused 0 (delta 0), pack-reused 24142
Receiving objects: 100% (24142/24142), 9.84 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (16972/16972), done.
ken@ken-desktop:~$ cd elvish/
ken@ken-desktop:~/elvish$ git checkout convert-to-go-mod
Branch 'convert-to-go-mod' set up to track remote branch 'convert-to-go-mod' from 'origin' by rebasing.
Switched to a new branch 'convert-to-go-mod'
ken@ken-desktop:~/elvish$ go build
go: finding github.com/mattn/go-isatty v0.0.6
go: finding github.com/boltdb/bolt v1.3.1
go: finding github.com/xiaq/persistent v0.0.0-20181118145548-6bf9d6baeece
go: finding github.com/kr/pty v1.1.3
go: finding golang.org/x/sys v0.0.0-20190309122539-980fc434d28e
go: finding golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
go: downloading github.com/xiaq/persistent v0.0.0-20181118145548-6bf9d6baeece
go: extracting github.com/xiaq/persistent v0.0.0-20181118145548-6bf9d6baeece
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading golang.org/x/sys v0.0.0-20190309122539-980fc434d28e
go: extracting github.com/boltdb/bolt v1.3.1
go: extracting golang.org/x/sys v0.0.0-20190309122539-980fc434d28e
ken@ken-desktop:~/elvish$
```

Go modules have been around for about a year, and it'll be roughly another year before Go 1.14 is out. The entire Go community has more or less switched over to Go modules. I only have done this as I am working on switching a different project (`u-root`) over to Go modules as well, and would like to have the upstream dependencies using Go modules as well.

I hope you can reconsider the position. Let me know if you have any questions. Thanks!

**Comment by xiaq** [comment]
Thanks for the information, I wasn't aware of that.

I did some research and the current situation is more complex than that: the default mode (`GO111MODULE=auto`) means that Go has two modes operation:

* When outside `GOPATH`, go.mod is respected and the vendor directory is ignored;

* When inside `GOPATH`, go.mod is ignored but the vendor directory is respected.

I do not want to break anyone's GOPATH workflow for now; this means that before `GO111MODULE=on` becomes the default for two major Go versions we'll need to maintain both go.mod and the vendor directory. I see that you are doing this, so that's good.

**Comment by xiaq** [comment]
A request for change before I can merge this: please let `go.mod` and `go.sum` reflect the current dependency versions (so that this PR keeps the `vendor` directory as is). You can update the versions if you want to in another PR.

**Comment by kenshaw** [comment]
Sorry for the delay in response: was travelling for work. I'll make the changes. Understand that with `go mod` there isn't much of a need to keep the vendor directory anymore, since it uses the exact dependency artifacts specified in the `go.sum` file.

**Pull request closed without merging**
