### PR TITLE
Allow histlist to be filtered case-insensitive

### PR DESCRIPTION
**Pull request by muesli**
You can press Ctrl+F to toggle case-sensitivity mode.

### CODE REVIEW

**Comment by xiaq** [comment]
I like this. Even though it is currently only for histlist mode, I think the natural plan is to support this in other modes as well. In completion mode, Ctrl-F is used for toggle **F**iltering, so we should use another key for consistency's sake.

Unfortunately we cannot use Ctrl-C because it sends SIGINT, nor Ctrl-I because it is the same as Tab. Ideas? It would be best if it can be justified in an interesting way. (Most keybindings in elvish are justified in one way or another, Ctrl-F coming from GUI applications, and Ctrl-L from browsers, for instance.)

**Comment by xiaq** [comment]
Hmm, the next-next level is to cycle through different matching algorithms (my favorite being subsequence matching where `am` matches **a**lgorith**m**), so we might come up with a key along that line.

Perhaps `Ctrl-M` for **m**atcher is a good one...

**Comment by muesli** [comment]
Isn't Ctrl-M usually [return]?

**Comment by xiaq** [comment]
Stupid me.

BTW, the grand picture of user-programmable filterer (what I called matcher in the last comment -- let's use filterer from now) is this project: https://github.com/elves/elvish/projects/1

**Pull request merged**
