### PR TITLE
Started writing file module, this is my first push. 

### PR DESCRIPTION
**Pull request by supreetsingh10**
This is by ave_santa666. This is the beginning of the file module. All feedback is welcome. Thank you for listening

### CODE REVIEW

**Comment by xiaq** [comment]
Thanks for the interest, but the commit doesn't build.

The contributor's manual has some guidance on how to build and test Elvish: https://github.com/elves/elvish/blob/master/CONTRIBUTING.md.

If you are unfamiliar with building and testing Go programs in general, I recommend that you start with [How to write Go code](https://golang.org/doc/code). Elvish is a multi-package program but the basics are the same.

**Comment by supreetsingh10** [comment]
Thank you for the review I will make it again. Thanks once again for the feedback

**Comment by krader1961** [comment]
@supreetsingh10, It's worth taking the time to install the tools documented in the section about formatting files in the CONTRIBUTING.md document. Configuring you editor to run the `goimports` tool will help you avoid the "unused import" error in this pull-request. It's also a good idea to get into the habit of running `go vet ./...`:

```
> go vet ./...
# src.elv.sh/pkg/eval/mods/file
vet: pkg/eval/mods/file/file.go:7:2: "src.elv.sh/pkg/eval/vals" imported but not used
```

For several months after I started contributing changes I avoided configuring my editor to automatically run `goimports` each time I saved a file. I eventually found it was easier to properly configure my editor than remembering to run `make style` to catch import errors.

Beyond that advice the package comment isn't properly formatted (missing a space after the `//`). The modification is also a bit too minimal as it doesn't do anything useful. Start by duplicating the `fclose` and `fopen` commands in the builtin module. **Do not** remove those commands from the builtin module -- mark them as deprecated and add a comment to that effect in the *NEXT-RELEASE.md* file.

**Comment by supreetsingh10** [comment]
Thank you very much Mr. @krader1961, I will get on fclose and fopen command. The major concern was how this module fits into the shell. I will look at how to fix the build issue and then make fclose and fopen. Thank you very much for the feedback.

**Comment by supreetsingh10** [comment]
I have installed the tools recommened in the contributing.md and I have written those functions and marked fopen and fclose as deprecated in builtin_io.go. I am looking for the part where I this links with the shell and file becomes available post build. I tried building the shell with the file module in the /pkg/eval/mods/ directory. It is not recognising the file, module.

**Comment by krader1961** [comment]
> I am looking for the part where I this links with the shell and file becomes available post build.

See the `InitRuntime` function in *pkg/shell/runtime.go*.

**Comment by krader1961** [comment]
Also, don't forget to create a *pkg/eval/mods/file/file_test.go* file that includes the `fopen` and `fclose` unit tests.

**Comment by supreetsingh10** [comment]
Great, the file module is building now, thanks to you. I am making the file_test.go, have added pipe and prclose to you. Thank you Mr. @krader1961 and Mr. @xiaq

**Comment by krader1961** [comment]
@supreetsingh10, It looks like this has been made obsolete by P.R. #1281 and therefore should be closed. If this is a prerequisite for P.R. #1281 then those commits should be squash-merged into this commit. There should be a single pull-request for the introduction of a "file" module.

**Comment by xiaq** [comment]
Closing in favor of #1281. In future, please stick to just one PR and use force pushes when appropriate.

**Pull request closed without merging**
