### PR TITLE
Improve error message when changing a read-only var

### LINKED ISSUE #255: Include variable name in error message when setting read-only variable
```
~> try failed; except false; tried
<interact>:1:20: eval error: read-only; cannot be set
try failed; except false; tried
```

### PR DESCRIPTION
**Pull request by krader1961**
Modifying a read-only var should include the var name in the error message.

Fixes #255

### CODE REVIEW

**Comment by krader1961** [comment]
I like the more accurate error messages produced by this change but am not happy with how intrusive it is. Here is an example of the more detailed error message:

```
> edit:selected-file = y
Exception: read-only variable edit:selected-file cannot be set
[tty 1], line 1: edit:selected-file = x
```

**Comment by krader1961** [comment]
On the other hand notice how much more the error from doing `true = x` is. Without this change:

```
Exception: read-only variable; cannot be set
[tty 140], line 1: true = x
```

With this change:

```
Exception: read-only variable builtin:true cannot be set
[tty 7], line 1: true = x
```

**Comment by xiaq** [comment]
> I like the more accurate error messages produced by this change but am not happy with how intrusive it is.

Indeed. Seeing how invasive the implementation needs to be to make the names of variables available to the error message, I feel this approach is not worth it.

It would be much less invasive to make the stack trace more accurate: for example, when running `set true = 1`, underline the `true` portion. This is slightly less obvious but at least the information is there.

Once we have that, another thing worth exploring is to somehow extract the variable name from the stack trace, and mix into the error message. Not sure how invasive that would be though.

**Comment by krader1961** [comment]
I'm pretty sure that doing this magically, rather than the straightforward way this P.R. does it, is going to be at least as intrusive and far harder for future readers of the code to understand. Also, consider the following examples for why something like this change is helpful. Yes, the `eval` example is contrived but perhaps there are similar examples more likely to be seen in the wild.

```
> a true b = 1 2 3
Exception: read-only variable builtin:true cannot be set
[tty 1], line 1: a true b = 1 2 3
> x = nil
> eval $x' = true'
Exception: read-only variable builtin:nil cannot be set
Traceback:
  [eval 1], line 1:
    nil = true
  [tty 3], line 1:
    eval $x' = true'
```

Also, consider if issue #1235 is implemented; allowing users to define read-only vars.

**Comment by xiaq** [comment]
> I'm pretty sure that doing this magically, rather than the straightforward way this P.R. does it, is going to be at least as intrusive and far harder for future readers of the code to understand.

I don't see how making the stack trace more accurate and underline the variable being assigned is "magical".

**Comment by krader1961** [comment]
My use of "magical" was in reference to constructing the warning message -- not the highlighting of the backtrace. However, the two are roughly equivalent. Note that if you're going to highlight the variable in the read-only assignment you should also highlight the value portion of the statement. I am basically saying that I think this straightforward solution is preferable to deriving the var name from the AST. Despite the fact it touches a lot of files; albeit in trivial ways.

**Comment by krader1961** [comment]
> ... I feel this approach is not worth it.

That might be true. But it does solve the problem in a straightforward manner that is easy to understand. And, perhaps more importantly, establishes a precedent for including adjunct information about each variable that is useful in many ways.

**Comment by xiaq** [comment]
I saw you closed the PR, but it's still worthwhile to clarify my opinion:

First, this is my main proposal. The outcome is slightly less ideal than having the variable name in the message, but the implementation is much more straightforward:

> It would be much less invasive to make the stack trace more accurate: for example, when running `set true = 1`, underline the `true` portion. This is slightly less obvious but at least the information is there.

Regarding your comment:

>  And, perhaps more importantly, establishes a precedent for including adjunct information about each variable that is useful in many ways.

I'm not sure whether such a precedent is worth establishing; so far it only solves this single problem. You seem to have some other problems in mind where such information is useful, but it's not obvious to me. If it does turn out to be quite useful, I'm certainly open to revisiting this decision.

**Comment by krader1961** [comment]
> I'm not sure whether such a precedent is worth establishing; so far it only solves this single problem. You seem to have some other problems in mind where such information is useful, but it's not obvious to me. If it does turn out to be quite useful, I'm certainly open to revisiting this decision.

I should have written "adjunct information..." that "could be useful" rather than "is useful in many ways". Which is to say, I can't help but think that the recently introduced `var` command opens up opportunities for new behavior. Such as a `&readonly` option as I [proposed here](https://github.com/elves/elvish/issues/1235). Yes, that doesn't require this change to produce improved error messages. However, I can't help but think other constraints (or attributes) might be better represented by var structure members than distinct var types.

Despite the above discussion I still think this straightforward solution is preferable to a hypothetical solution involving the parser that seems unlikely to be implemented in my lifetime. In no small part because that solution is greatly complicated by the reasonable expectation it highlight both the variable and value portion of the statement.

**Comment by krader1961** [comment]
I also closed this pull-request because I don't really care if assignment to read-only var error messages is improved. I do, however, care about improved logging and thus want to focus my resources on P.R. #1229.

**Comment by xiaq** [comment]
> Despite the above discussion I still think this straightforward solution is preferable to a hypothetical solution involving the parser that seems unlikely to be implemented in my lifetime.

The "hypothetical solution involving the parser that seems unlikely to be implemented in my lifetime" was implemented in a33ecb2da4ce02954fedad47ed40f01903f5ab4d; the change only takes 4 lines - the opcode structure actually already contains the range information of each LHS variable, they were just not being passed to `fm.errorpf`. If your goal was to provoke me into implementing this you have succeeded. :)

**Pull request closed without merging**
