### PR TITLE
Fix:https://github.com/elves/elvish/issues/1178

### PR DESCRIPTION
**Pull request by mrlzh**

### CODE REVIEW

**Comment by krader1961** [comment]
Your problem statement says "impossible to delete words" using Ctrl-H in history mode. But the Backspace key deletes a single rune (i.e., character), not a word. Did you mean to say "impossible to delete characters/runes"? Or are you referring to making Alt-Ctrl-H behave the same as Alt-Backspace?

Also, your change implements a needlessly opaque, and confusing, definition of `'H'` as `0x48` and giving that rune a misleading symbolic name.

**Comment by xiaq** [comment]
Hi, thanks for the PR. As @krader1961 pointed out, 0x48 is just the letter `H`, there is no need to define a constant for it.

@krader1961, I believe @mrlzh meant using Backspace to delete runes; some terminals send ^H when Backspace is pressed.

**Comment by krader1961** [comment]
> some terminals send ^H when Backspace is pressed.

Yes, that is true. 😄 In fact, hardware terminals such as the Televideo 9xx series (including the model 925 and 950 that I used three decades ago) supported configuring which character that key transmitted but they defaulted to Ctrl-H. The question is whether Delete (0x7F) (mistakenly labeled "Backspace" in the source code) and Ctrl-H (0x08 aka "bs" in ASCII) should be equivalent by default. My vote is yes, the two runes should behave identically by default. See, for example, https://www.computerhope.com/issues/ch001389.htm.

**Comment by xiaq** [comment]
#1178 was fixed in b11fe9d.

**Pull request closed without merging**
